### ISSUE TITLE
Geofency ist nicht in der Liste "Installieren aus eigener URL" enthalten

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.geofency#15]
Dadurch kann eine Aktualisierung des Adapters nur aus der Registerkarte "Beliebige URL eingeben" aktualisiert werden. In der Auflistung der Adapter taucht "Geofency" derzeit nicht auf.

![github_adapter](https://user-images.githubusercontent.com/30980239/29494167-877e9ed4-85a4-11e7-83f8-65381855dbde.png)

**Comment by Apollon77** [comment]
Das komme manchmal vor ... habe noch nicht rausgefunden wann/warum ... ABer generell ist alles drin was im Repositorry ist und bei mir taucht er da auch auf.
Versuch bitte mal ein "iobroker upload geofency" ... und nen Restart von ioBroker

**Comment by BramTown** [comment]
Moin Apollon,
ich habe "iobroker upload geofency" über die Konsole (puTTY) eingegeben - war das so gemeint?
Anschließend einen Reboot vom Raspi durchgeführt - das Ergebnis ist das gleiche - geofency taucht nicht in der Übersicht auf.
Ist aber auch kein Beinbruch; ich habe verstanden, dass es mitunter mal vorkommen kann, es also nicht an einer entwicklungsseitigen Einstellung im Adapter liegt - ich kann mir ja durch Eingabe der Github Seite behelfen :-)
Ciao und Gruß,
Heiko

**Comment by Apollon77** [comment]
Immer noch nicht drin?

**Comment by BramTown** [comment]
Ich habe gerade nachgeschaut - Doch ist nun drinnen !!
