### ISSUE TITLE
password check invalid

### ISSUE THREAD

**Issue by dschaedl** [ioBroker/ioBroker.geofency#18]
Line 139: if ((username != check_user) || (password == check_pass)) {
it should be: password != check_pass

**Comment by Apollon77** [comment]
In general the whole Authentication is broken in the App ... they are simply not sending credentials with the call ... so this code (while wrong, will fix it) is never really used :-(

**Comment by Apollon77** [comment]
Available on Github. Please test this version and tell me if Auth works ?!

**Comment by dschaedl** [comment]
authentication works for me (and it did not work 1h ago ;-))

**Comment by Apollon77** [comment]
hast Du auch mal den Fehlerfall getestet? (also andere logindaten gesendet als konfiguriert)

... oder ich hab bei meinen ganzen tests echt diesen fehler übersehenn ... *ggggrrrr*

**Comment by Apollon77** [comment]
0.3.2 auf Github und ab morgen im "Latest"
