### ISSUE TITLE
Feature-Request

### ISSUE THREAD

**Issue by Pixeladler** [ioBroker/ioBroker.geofency#20]
Da ich im Englischen nicht so gut bin und zusätzlich das erste mal unter GitHub schreibe, bitte ich um Nachsicht.

Die iOS App. Geofency sendet unter "POST Format" -> JSON-enkodiert folgendes:

> [id] -> {Identifier des Ortes}
[name] -> {Ortsname}
[entry] -> {1 für Eintritt, 0 für Austritt}
[date] -> {Zeitstempel des Events}
[latitude] -> {Breitengrad des Ortes}
[longiitude] -> {Längengrad des Ortes}
[address] -> {Adressstring des Ortes}
[radius] -> {Überwachungsradius}
[device] -> {iOS Gerätekennung}
[beaconUUID] -> {iBeacon UUID}
[major] -> {iBeacon Major Nummer}
[minor] -> {iBeacon Minor Nummer}
[currentLatitude] -> {Proximity Breitengrad}
[currentLongitude] -> {Proximity Längengrad}
[wifiSSID] -> {SSID des verbundenen WLAN}
[wifiBSSID] -> {BSSID des verbundenen WLAN}
[motion] -> {Bewegungstyp: Gehen, Radfahren, etc.}

Folgende Werte sind aktuell als **WERT** im Geofency/ioBroker Adapter enthalten:

> [entry] -> {1 für Eintritt, 0 für Austritt}
[date] -> {Zeitstempel des Events}

Ich würde mich sehr freuen, wenn die oben genannten Werte auch als tatsächlicher **WERT** als **WERT** im ioBroker zu Verfügung stehen würden.
Derzeit wird z.B. der Ort als Ordner gelistetet, was z.B. bei meiner AIO CREATOR NEO (mediola) Darstellung nicht Dargestellt werden kann. (nur Werte)

Ich hoffe es ist verständlich und würde mich riesig freuen, wenn dieser Umfangreiche Wunsch in Erfüllung gehen würde.

**Comment by Apollon77** [comment]
Please check GitHub version ... if still interested please provide feedback
