### ISSUE TITLE
geofency adapter crashes when using geofency app on iPhone

### ISSUE THREAD

**Issue by DFS-90** [ioBroker/ioBroker.geofency#60]
Good morning,

I'm trying to establish a proximity detection at home via iBeacon and geofency app on my iPhone..
I installed the most current version of the geofency adapter.

Whenever I try to sign in at home via geofency "test mode", the adapter crashes with the attached error.
I already set the geofency app to use JSON.

Does anybody know how to solve this error?

Thanks in advance,

David

![Screenshot 2022-01-16 113048](https://user-images.githubusercontent.com/87578070/149656348-e2d8c760-55da-4701-a6d5-d201e45ac287.jpg)

**Comment by Apollon77** [comment]
It seems that the [ and ] in your name is causing it somehow. Please run instance in debug log to get more details

**Comment by DFS-90** [comment]
That did the trick - thanks!


Am 16.01.2022 um 15:11 schrieb Ingo Fischer ***@***.***>:

﻿


It seems that the [ and ] in your name is causing it somehow. Please run instance in debug log to get more details

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
