### ISSUE TITLE
This object will not be created in future versions.

### ISSUE THREAD

**Issue by aski71** [ioBroker/ioBroker.geofency#66]
Hi,

I received these messages in the log with the message to report this to the developer:

2022-02-09 17:26:06.915 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | --
geofency.0 | 2022-02-09 17:26:06.913 | warn | Object geofency.0.atHomeCount is invalid: Default value has to be type "number" but received type "object"
geofency.0 | 2022-02-09 17:26:05.518 | warn | This object will not be created in future versions. Please report this to the developer.
geofency.0 | 2022-02-09 17:26:05.410 | warn | Object geofency.0.atHome is invalid: Default value has to be type "string" but received type "number"

**Versions:**  
 - Adapter version: 1.0.3
 - JS-Controller version: 4.0.5
 - Node version:164.0
 - Operating system: Ubuntu 18.04

**Comment by aski71** [comment]
Interesting that the messages are cut off. So here they are again:


Object geofency.0.atHomeCount is invalid: Default value has to be type "number" but received type "object"

Object geofency.0.atHome is invalid: Default value has to be type "string" but received type "number"

**Comment by aski71** [comment]
Any thoughts?

**Comment by Apollon77** [comment]
will be fixed in next update
