### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by aski71** [ioBroker/ioBroker.geofency#67]
Hi,

I had this uncaught exception today.
No idea what triggered it.

.homie | 2022-02-24 13:29:30.664 | error | instance system.adapter.geofency.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
geofency.0 | 2022-02-24 13:29:29.996 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
geofency.0 | 2022-02-24 13:29:29.994 | info | terminating
geofency.0 | 2022-02-24 13:29:29.974 | error | Unexpected token < in JSON at position 0
geofency.0 | 2022-02-24 13:29:29.973 | error | SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.geofency/geofency.js:167:32) at IncomingMessage.emit (node:events:532:35) at endReadableNT (node:internal/streams/readable:1346:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)
geofency.0 | 2022-02-24 13:29:29.969 | error | uncaught exception: Unexpected token < in JSON at position 0

**Comment by Apollon77** [comment]
will be fixed in next version
