### ISSUE TITLE
Beschreibung Datenpunkt lastLeave ist falsch

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.geofency#8]
In der Beschreibung für den Datenpunkt lastLeave steht lastEnter

**Comment by GermanBluefox** [comment]
Is it still open?

**Comment by ruhr70** [comment]
in der Version 0.1.4.
bestehende Installation ohne Neuinstallation: ja, immer noch offen

Adapterneuinstallation nicht getestet

**Comment by simpixo** [comment]
Auch in der Versil 0.1.5 wird das lastLeave nicht befüllt! Bis 01.10 wurde das Objekt aber definitiv mit dem richtigen LEAVE Datum befüllt

**Comment by Apollon77** [comment]
solved mit 0.1.6 ... muss nur noch gepublished werden
