### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by Hunduster** [ioBroker/ioBroker.geofency#87]
**Describe the bug**  
The built-in authentication seems to be without function. It is possible to submit a valid webhook without and with false login data and thus write corresponding values. 

**To Reproduce**  
1. Go to 'Geofency iOS App'
2. Click on any of your Webhooks
3. Clear the authentication fields and set up the webhook
3.1 Alternatively enter wrong authentication data

**Expected behaviour**  
If authentication is switched on in the adapter, I expect an authentication error in case of wrong or missing login data.

**Versions:**  
 - Adapter version: 1.1.1
 - JS-Controller version: 4.0.23
 - Node version: 14.20.0
 - Operating system: Ubuntu 22.04

**Comment by Apollon77** [comment]
Please show the configuration where youz setup the authentication and how

**Comment by Hunduster** [comment]
> Please show the configuration where youz setup the authentication and how

![image](https://user-images.githubusercontent.com/110684064/183138077-688149bb-b8dc-4825-9298-431e090b43f1.png)
Enclosed is the screenshot.

I have now used a "dummy" password here.

It doesn't matter what I enter here. The instance always accepts the webhooks of the app and writes the values into the objects.

I noticed this when I set up the app on another iPhone and forgot to set the authentication. But the values were transmitted correctly.

**Comment by GermanBluefox** [comment]
Please test 1.2.1

**Comment by Hunduster** [comment]
> Please test 1.2.1

Unfortunately, it does not work.

I installed the new version directly from Github in ioBroker. The instance runs sucessful in ioBroker. When I try to send a webhook, I get the status code 403.

I tried to submit the webhook via my reverse proxy. Status code 403

Via DNAT: ERR_CONNECTION_TIMED_OUT

Internal IP: ERR_CONNECTION_TIMED_OUT

**Comment by GermanBluefox** [comment]
I retest the check of Login/Password. Try to enter password anew in the configuration.

**Comment by Hunduster** [comment]
Unfortunately also without success.

I have updated version 1.2.2 from Github and tested up and down. With the old password, with a new password, etc.  I now always get HTTP status code 401 unauthorized. In the ioBroker log I still get this message:

![image](https://user-images.githubusercontent.com/110684064/187416423-fd6cfde4-4d5c-4c73-a8b2-07783b16da82.png)

**Comment by Apollon77** [comment]
And in the app the username/password is entered? Please set adapter to debug log and try again ... you should see a log like "Authorization Header is: ..." ...whats in there?
And which node.js version you use?

**Comment by adieball** [comment]
Bei mir kommt auch nur Authorization Header missing but user/pass defined
Auch ein debug log bringt nicht mehr Informationen.
<img width="1007" alt="Screenshot 2022-09-18 at 16 45 58" src="https://user-images.githubusercontent.com/6988389/190912989-c5b61bd7-c174-4b89-982a-2a9cdc44cbb7.png">

**Comment by Apollon77** [comment]
Also mit Debug log MUSS diese Zeile kommen im Log: https://github.com/ioBroker/ioBroker.geofency/blob/master/main.js#L131

**Comment by adieball** [comment]
Ja, my fault.
Es kommt davor: Authorization Header is: undefined

Geofency (App): 7.5 (2516)
Iobroker Geofency: 1.2.2
Node.ja: v16.16.0

**Comment by Apollon77** [comment]
I did debug it to the point that when I ue the current iOS App it really do not send any authentication header even if specified. So for me it seems to be an issue of the app that the credentials entered there are not send out in webhooks.

I have contacted the App developer

**Comment by Apollon77** [comment]
Ok, I also tested with Curl ... If uername/password is provided the adapter works as expected, so it is really the app not providing the details.

**Comment by Hunduster** [comment]
Sorry, dass ich mich solange nicht gemeldet habe. Krank, Urlaub etc.
@Apollon77 vielen Dank fürs Kümmern!

**Comment by Apollon77** [comment]
I had contact with the app developer and tested a beta version of the app and there it was changed to be compatible to what the ioBroker adapter expects. I will inform as soon as I know more for a release of this version
