### ISSUE TITLE
After update: Cannot start https server: SSL required but no certificates selected!

### ISSUE THREAD

**Issue by aski71** [ioBroker/ioBroker.geofency#89]
I updated the adapter to the latest version 1.2.1
Now it does not find my certificates anymore.
I have installed letsencrypt certificates on my machine. Those are still shown in the overall iobroker settings under "certificates" and point to the correct files.
thanks for quick help.

**Comment by aski71** [comment]
Is somebody in here?

**Comment by Apollon77** [comment]
please show the config of the adapter? and also certificates in iobroker settings
